import { Page } from './docs-types';
export const MOCK_PAGES: Page[] = [
  {
    id: 'home',
    title: 'Home',
    slug: 'home',
    parentId: null,
    order: 0,
    status: 'Published',
    lastUpdated: '2025-11-10T10:00:00Z',
    content: {
      time: 1731148800000,
      version: '2.29.0',
      blocks: [
        { type: 'header', data: { text: 'Cockpit Design System', level: 1 } },
        { type: 'paragraph', data: { text: 'Welcome to the single source of truth for the Cockpit Design System (CDS). This is where we merge design, code, and content into a single, living ecosystem.' } },
        { type: 'header', data: { text: 'Mission & Principles', level: 2 } },
        { type: 'list', data: { style: 'ordered', items: [
          '<strong>Clarity:</strong> Eliminate ambiguity. Our components and patterns should be intuitive and easy to understand.',
          '<strong>Efficiency:</strong> Streamline workflows. Empower teams to build high-quality experiences faster.',
          '<strong>Consistency:</strong> Create a unified experience. Every part of our product should feel like it belongs.',
          '<strong>Accessibility:</strong> Build for everyone. Ensure our products are usable by people of all abilities.',
        ]}},
      ],
    },
  },
  {
    id: 'foundations',
    title: 'Foundations',
    slug: 'foundations',
    parentId: null,
    order: 1,
    status: 'Published',
    lastUpdated: '2025-11-10T10:00:00Z',
    content: {
      time: 1731148800000,
      version: '2.29.0',
      blocks: [
        { type: 'header', data: { text: 'Foundations', level: 1 } },
        { type: 'paragraph', data: { text: 'Foundations are the core visual and interactive principles that define the Cockpit Design System. They are the building blocks of our design language.' } },
      ],
    },
  },
  {
    id: 'color',
    title: 'Color',
    slug: 'color',
    parentId: 'foundations',
    order: 0,
    status: 'Published',
    lastUpdated: '2025-11-10T10:00:00Z',
    content: {
      time: 1731148800000,
      version: '2.29.0',
      blocks: [
        { type: 'header', data: { text: 'Color', level: 1 } },
        { type: 'paragraph', data: { text: 'Our color palette is designed to be clear, accessible, and harmonious. It includes brand colors, semantic tokens for UI states, and a neutral gray scale.' } },
        { type: 'header', data: { text: 'Brand Colors', level: 2 } },
        { type: 'paragraph', data: { text: 'These colors represent our brand identity.' } },
        { type: 'header', data: { text: 'Semantic Tokens', level: 2 } },
        { type: 'paragraph', data: { text: 'These tokens communicate meaning and state, such as success, warning, or danger.' } },
      ],
    },
  },
  {
    id: 'typography',
    title: 'Typography',
    slug: 'typography',
    parentId: 'foundations',
    order: 1,
    status: 'Published',
    lastUpdated: '2025-11-10T10:00:00Z',
    content: {
      time: 1731148800000,
      version: '2.29.0',
      blocks: [
        { type: 'header', data: { text: 'Typography', level: 1 } },
        { type: 'paragraph', data: { text: 'Consistent typography creates a clear visual hierarchy and improves readability. We use the Inter font family for all UI text.' } },
      ],
    },
  },
  {
    id: 'components',
    title: 'Components',
    slug: 'components',
    parentId: null,
    order: 2,
    status: 'Published',
    lastUpdated: '2025-11-10T10:00:00Z',
    content: {
      time: 1731148800000,
      version: '2.29.0',
      blocks: [
        { type: 'header', data: { text: 'Components', level: 1 } },
        { type: 'paragraph', data: { text: 'Components are reusable UI elements that form the building blocks of our applications.' } },
      ],
    },
  },
  {
    id: 'button',
    title: 'Button',
    slug: 'button',
    parentId: 'components',
    order: 0,
    status: 'Published',
    lastUpdated: '2025-11-10T10:00:00Z',
    content: {
      time: 1731148800000,
      version: '2.29.0',
      blocks: [
        { type: 'header', data: { text: 'Button', level: 1 } },
        { type: 'paragraph', data: { text: 'Buttons are used to trigger actions or events. They are one of the most fundamental interactive elements.' } },
        { type: 'header', data: { text: 'Usage', level: 2 } },
        { type: 'paragraph', data: { text: 'Use buttons for primary actions you want to encourage users to take.' } },
        { type: 'code', data: { code: "<Button variant='primary'>Click me</Button>" } },
        { type: 'header', data: { text: 'Variants', level: 3 } },
        { type: 'list', data: { style: 'unordered', items: ['Primary', 'Secondary', 'Destructive', 'Outline', 'Ghost', 'Link']}},
      ],
    },
  },
];